//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firmarStdSri.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://facturas.acklins.net/WsSiteCargasDescargasAck/wsGrabarDoc.asmx")]
        public string firmarStdSri_wsGrabarDocV3_wsGrabarDoc {
            get {
                return ((string)(this["firmarStdSri_wsGrabarDocV3_wsGrabarDoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://facturas.acklins.net/WsSiteCargasDescargasAckTest/wsGrabarDoc.asmx")]
        public string firmarStdSri_wsGrabarDocV3Test_wsGrabarDoc {
            get {
                return ((string)(this["firmarStdSri_wsGrabarDocV3Test_wsGrabarDoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://facturas.acklins.net/wsArchivosElectronicosOffline/wsarchivoselectronicoso" +
            "ffline.asmx")]
        public string firmarStdSri_subirDocumentosElectronicos_wsarchivoselectronicosoffline {
            get {
                return ((string)(this["firmarStdSri_subirDocumentosElectronicos_wsarchivoselectronicosoffline"]));
            }
        }
    }
}
